; Беларуская лакалізацыя Inno Setup 7 для інсталятараў GTA GXT Editor.
; UTF-8 без BOM.

[LangOptions]
LanguageName=Беларуская
LanguageID=$0423
LanguageCodePage=0
DialogFontName=Segoe UI
DialogFontSize=9
WelcomeFontName=Segoe UI
WelcomeFontSize=12
TitleFontName=Segoe UI
TitleFontSize=29
CopyrightFontName=Segoe UI
CopyrightFontSize=8

[Messages]
SelectLanguageTitle=Выбар мовы ўсталёўшчыка
SelectLanguageLabel=Выберыце мову, якая будзе выкарыстоўвацца падчас усталявання:
ButtonBack=< &Назад
ButtonNext=&Далей >
ButtonInstall=&Усталяваць
ButtonOK=OK
ButtonCancel=Скасаваць
ButtonYes=&Так
ButtonYesToAll=Так для &ўсіх
ButtonNo=&Не
ButtonNoToAll=Не для ў&сіх
ButtonFinish=&Завяршыць
ButtonBrowse=&Агляд...
ButtonWizardBrowse=&Агляд...
ButtonNewFolder=&Стварыць папку
SetupAppTitle=Усталяванне
SetupWindowTitle=Усталяванне — %1
UninstallAppTitle=Выдаленне
UninstallAppFullTitle=Выдаленне %1
InformationTitle=Звесткі
ConfirmTitle=Пацвярджэнне
ErrorTitle=Памылка
SetupLdrStartupMessage=Гэта праграма ўсталюе %1. Працягнуць?
LdrCannotCreateTemp=Немагчыма стварыць часовы файл. Усталяванне перапынена.
LdrCannotExecTemp=Немагчыма запусціць файл у часовай папцы. Усталяванне перапынена.
HelpTextNote=
LastErrorMessage=%1.%n%nПамылка %2: %3
SetupFileMissing=Файл %1 адсутнічае ў папцы ўсталёўшчыка. Выпраўце праблему або атрымайце новую копію праграмы.
SetupFileCorrupt=Файлы ўсталёўшчыка пашкоджаныя. Атрымайце новую копію праграмы.
SetupFileCorruptOrWrongVer=Файлы ўсталёўшчыка пашкоджаныя або несумяшчальныя з гэтай версіяй. Выпраўце праблему або атрымайце новую копію праграмы.
InvalidParameter=Памылковы параметр каманднага радка:%n%n%1
SetupAlreadyRunning=Усталёўшчык ужо запушчаны.
WindowsVersionNotSupported=Гэтая праграма не падтрымлівае версію Windows, усталяваную на гэтым камп'ютары.
WindowsServicePackRequired=Праграме патрэбны %1 Service Pack %2 або навейшы.
NotOnThisPlatform=Праграма не працуе на %1.
OnlyOnThisPlatform=Праграма працуе толькі на %1.
OnlyOnTheseArchitectures=Праграма працуе толькі на наступных архітэктурах Windows:%n%n%1
WinVersionTooLowError=Праграме патрэбна %1 версіі %2 або навейшая.
WinVersionTooHighError=Праграма не можа быць усталяваная ў %1 версіі %2 або навейшай.
AdminPrivilegesRequired=Для ўсталявання неабходныя правы адміністратара.
PowerUserPrivilegesRequired=Для ўсталявання неабходныя правы адміністратара або дасведчанага карыстальніка.
SetupAppRunningError=Усталёўшчык выявіў, што %1 зараз працуе.%n%nЗакрыйце ўсе яго асобнікі і націсніце OK або Скасаваць, каб выйсці.
UninstallAppRunningError=Праграма выдалення выявіла, што %1 зараз працуе.%n%nЗакрыйце ўсе яго асобнікі і націсніце OK або Скасаваць, каб выйсці.
PrivilegesRequiredOverrideTitle=Выбар рэжыму ўсталявання
PrivilegesRequiredOverrideInstruction=Выберыце рэжым усталявання
PrivilegesRequiredOverrideText1=Выберыце, для каго трэба ўсталяваць %1.
PrivilegesRequiredOverrideText2=Усталяваць толькі для мяне
PrivilegesRequiredOverrideAllUsers=Усталяваць для &ўсіх карыстальнікаў
PrivilegesRequiredOverrideAllUsersRecommended=Усталяваць для &ўсіх карыстальнікаў (рэкамендуецца)
PrivilegesRequiredOverrideCurrentUser=Усталяваць толькі для &мяне
ErrorCreatingDir=Немагчыма стварыць папку «%1».
ErrorTooManyFiles=Немагчыма стварыць больш файлаў. Закрыйце іншыя праграмы і паўтарыце спробу.
ExitSetupTitle=Выхад з усталёўшчыка
ExitSetupMessage=Усталяванне не завершана. Калі выйсці зараз, праграма не будзе ўсталяваная.%n%nМайстар можна запусціць пазней.%n%nВыйсці?
AboutSetupMenuItem=&Пра ўсталёўшчык...
AboutSetupTitle=Пра ўсталёўшчык
AboutSetupMessage=%1, версія %2%n%3%n%n%1: %4%n%5%n%nhttps://www.innosetup.com/
AboutSetupNote=
TranslatorNote=Беларуская лакалізацыя GTA GXT Editor
BeveledLabel=
BrowseDialogTitle=Выбар папкі
BrowseDialogLabel=Выберыце папку ў спісе і націсніце OK.
NewFolderName=Новая папка
WelcomeLabel1=Вітаем у майстры ўсталявання [name]
WelcomeLabel2=Праграма ўсталюе [name/ver] на камп'ютар.%n%nПерад працягам рэкамендуецца закрыць іншыя праграмы.
WizardSelectDir=Выбар папкі гульні
SelectDirDesc=Дзе знаходзіцца Grand Theft Auto: Vice City?
SelectDirLabel3=Файлы [name] будуць усталяваныя ў наступную папку гульні.
SelectDirBrowseLabel=Каб працягнуць, націсніце «Далей». Каб выбраць іншую папку, націсніце «Агляд».
DiskSpaceGBLabel=Патрэбна не менш за [gb] ГБ вольнага месца.
DiskSpaceMBLabel=Патрэбна не менш за [mb] МБ вольнага месца.
CannotInstallToNetworkDrive=Усталяванне на сеткавы дыск немагчыма.
CannotInstallToUNCPath=Усталяванне па UNC-шляху немагчыма.
InvalidPath=Трэба ўвесці поўны шлях з літарай дыска, напрыклад:%n%nC:\Program Files\My Program%n%nабо UNC-шлях у выглядзе:%n%n\\server\share
InvalidDrive=Дыск або сеткавы шлях не існуе ці недаступны. Выберыце іншы шлях.
DiskSpaceWarningTitle=Недастаткова месца
DiskSpaceWarning=Для ўсталявання патрэбна не менш за %1 КБ, але на выбраным дыску даступна толькі %2 КБ.%n%nПрацягнуць?
DirNameTooLong=Імя папкі або шлях занадта доўгі.
InvalidDirName=Імя папкі памылковае.
BadDirName32=Імя папкі не можа змяшчаць наступныя знакі:%n%n%1
DirExistsTitle=Папка існуе
DirExists=Папка:%n%n%1%n%nужо існуе. Усталяваць у яе?
DirDoesntExistTitle=Папка не існуе
DirDoesntExist=Папка:%n%n%1%n%nне існуе. Стварыць яе?
WizardReady=Гатова да ўсталявання
ReadyLabel1=Усё гатова да ўсталявання [name] на камп'ютар.
ReadyLabel2a=Націсніце «Усталяваць», каб працягнуць, або «Назад», каб змяніць налады.
ReadyLabel2b=Націсніце «Усталяваць», каб працягнуць.
ReadyMemoDir=Папка гульні:
ReadyMemoType=Тып усталявання:
ReadyMemoComponents=Выбраныя кампаненты:
ReadyMemoGroup=Папка меню «Пуск»:
ReadyMemoTasks=Дадатковыя задачы:
WizardPreparing=Падрыхтоўка да ўсталявання
PreparingDesc=Усталёўшчык рыхтуецца ўсталяваць [name].
PreviousInstallNotCompleted=Папярэдняе ўсталяванне або выдаленне не завершана. Для завяршэння патрэбна перазагрузка.%n%nПасля перазагрузкі запусціце ўсталёўшчык зноў.
CannotContinue=Немагчыма працягнуць. Выпраўце праблему і паўтарыце спробу.
ApplicationsFound=Наступныя праграмы выкарыстоўваюць файлы, якія трэба абнавіць. Рэкамендуецца дазволіць усталёўшчыку аўтаматычна закрыць іх.
ApplicationsFound2=Наступныя праграмы выкарыстоўваюць файлы, якія трэба абнавіць. Рэкамендуецца закрыць іх уручную.
CloseApplications=&Аўтаматычна закрыць праграмы
DontCloseApplications=&Не закрываць праграмы
ErrorCloseApplications=Не ўдалося закрыць усе праграмы. Рэкамендуецца закрыць іх уручную.
PrepareToInstallNeedsRestart=Усталёўшчыку трэба перазапусціць камп'ютар. Пасля перазагрузкі запусціце яго зноў.%n%nПеразапусціць зараз?
WizardInstalling=Усталяванне
InstallingLabel=Пачакайце, пакуль [name] усталёўваецца на камп'ютар.
FinishedHeadingLabel=Усталяванне [name] завершана
FinishedLabelNoIcons=Праграма [name] паспяхова ўсталяваная.
FinishedLabel=Праграма [name] паспяхова ўсталяваная.
FinishedRestartLabel=Для завяршэння ўсталявання [name] трэба перазапусціць камп'ютар. Зрабіць гэта зараз?
FinishedRestartMessage=Для завяршэння ўсталявання [name] трэба перазапусціць камп'ютар.%n%nЗрабіць гэта зараз?
ShowReadmeCheck=Паказаць README
YesRadio=&Так, перазапусціць зараз
NoRadio=&Не, перазапусціць пазней
RunEntryExec=Запусціць %1
RunEntryShellExec=Адкрыць %1
ChangeDiskTitle=Патрэбны наступны носьбіт
SelectDiskLabel2=Устаўце дыск %1 і націсніце OK.%n%nКалі файлы знаходзяцца ў іншай папцы, пакажыце яе ніжэй.
PathLabel=Шлях:
FileNotInDir2=Файл «%1» не знойдзены ў «%2». Устаўце правільны дыск або выберыце іншую папку.
SelectDirectoryLabel=Пакажыце месцазнаходжанне наступнага дыска.
SetupAborted=Усталяванне не завершана.%n%nВыпраўце праблему і запусціце ўсталёўшчык зноў.
StatusClosingApplications=Закрыццё праграм...
StatusCreateDirs=Стварэнне папак...
StatusExtractFiles=Распакоўванне файлаў...
StatusCreateIcons=Стварэнне ярлыкоў...
StatusCreateIniEntries=Стварэнне запісаў INI...
StatusCreateRegistryEntries=Стварэнне запісаў рэестра...
StatusRegisterFiles=Рэгістрацыя файлаў...
StatusSavingUninstall=Захаванне звестак для выдалення...
StatusRunProgram=Завяршэнне ўсталявання...
StatusRestartingApplications=Перазапуск праграм...
StatusRollback=Адкат змяненняў...
ErrorInternal2=Унутраная памылка: %1
ErrorFunctionFailedNoCode=%1 не выканана
ErrorFunctionFailed=%1 не выканана; код %2
ErrorFunctionFailedWithMessage=%1 не выканана; код %2.%n%3
ErrorExecutingProgram=Немагчыма запусціць файл:%n%1
ErrorRegOpenKey=Памылка адкрыцця ключа рэестра:%n%1\%2
ErrorRegCreateKey=Памылка стварэння ключа рэестра:%n%1\%2
ErrorRegWriteKey=Памылка запісу ў ключ рэестра:%n%1\%2
ErrorIniEntry=Памылка стварэння запісу INI у файле «%1».
FileAbortRetryIgnore=Націсніце «Паўтарыць», каб паспрабаваць зноў, «Ігнараваць», каб прапусціць файл, або «Перапыніць», каб спыніць усталяванне.
FileAbortRetryIgnore2=Націсніце «Паўтарыць», каб паспрабаваць зноў, «Ігнараваць», каб працягнуць, або «Перапыніць», каб спыніць усталяванне.
SourceIsCorrupted=Зыходны файл пашкоджаны
SourceDoesntExist=Зыходны файл «%1» не існуе
ExistingFileReadOnly=Файл толькі для чытання.%n%nПеразапісаць яго?
ErrorReadingExistingDest=Памылка чытання існуючага файла:
ErrorChangingAttr=Памылка змянення атрыбутаў файла:
ErrorCreatingTemp=Памылка стварэння файла ў папцы прызначэння:
ErrorReadingSource=Памылка чытання зыходнага файла:
ErrorCopying=Памылка капіявання файла:
ErrorReplacingExistingFile=Памылка замены існуючага файла:
ErrorRestartReplace=Немагчыма запланаваць замену файла пасля перазагрузкі:
ErrorRenamingTemp=Памылка перайменавання файла ў папцы прызначэння:
ErrorRegisterServer=Немагчыма зарэгістраваць DLL/OCX: %1
ErrorRegSvr32Failed=RegSvr32 завяршыўся з кодам %1
ErrorRegisterTypeLib=Немагчыма зарэгістраваць бібліятэку тыпаў: %1
ErrorOpeningReadme=Немагчыма адкрыць README.
ErrorRestartingComputer=Не ўдалося перазапусціць камп'ютар. Зрабіце гэта ўручную.
UninstallNotFound=Файл «%1» не існуе. Выдаленне немагчыма.
UninstallOpenError=Файл «%1» немагчыма адкрыць. Выдаленне немагчыма.%n%nПамылка %2: %3
UninstallUnsupportedVer=Файл «%1» мае невядомы фармат. Выдаленне немагчыма.
UninstallUnknownEntry=У журнале выдалення знойдзены невядомы запіс (%1).
ConfirmUninstall=Сапраўды цалкам выдаліць %1 і ўсе яго кампаненты?
UninstallOnlyOnWin64=Гэтую праграму можна выдаліць толькі ў 64-бітнай Windows.
OnlyAdminCanUninstall=Праграму можа выдаліць толькі карыстальнік з правамі адміністратара.
UninstallStatusLabel=Пачакайце, пакуль %1 выдаляецца з камп'ютара.
UninstalledAll=%1 паспяхова выдалены з камп'ютара.
UninstalledMost=Выдаленне %1 завершана.%n%nНекаторыя элементы не атрымалася выдаліць. Іх можна выдаліць уручную.
UninstalledAndNeedsRestart=Для завяршэння выдалення %1 трэба перазапусціць камп'ютар.%n%nЗрабіць гэта зараз?
UninstallDataCorrupted=Файл «%1» пашкоджаны. Выдаленне немагчыма.
ConfirmDeleteSharedFileTitle=Выдаліць агульны файл?
ConfirmDeleteSharedFile2=Сістэма паказвае, што гэты агульны файл больш не выкарыстоўваецца. Выдаліць яго?%n%nКалі іншыя праграмы ўсё яшчэ выкарыстоўваюць файл, яны могуць перастаць працаваць. Калі вы не ўпэўненыя, выберыце «Не».
SharedFileNameLabel=Імя файла:
SharedFileLocationLabel=Размяшчэнне:
WizardUninstalling=Выдаленне
UninstallingLabel=Пачакайце, пакуль %1 выдаляецца з камп'ютара.
PrivilegesRequiredOverrideCurrentUserRecommended=Усталяваць толькі для &мяне (рэкамендуецца)
ErrorTooManyFilesInDir=Немагчыма стварыць файл у папцы «%1», бо яна змяшчае зашмат файлаў
ClickNext=Націсніце «Далей», каб працягнуць, або «Скасаваць», каб выйсці з усталёўшчыка.
WizardPassword=Пароль
PasswordLabel1=Гэтае ўсталяванне абароненае паролем.
PasswordLabel3=Увядзіце пароль і націсніце «Далей». Рэгістр літар у паролі мае значэнне.
PasswordEditLabel=&Пароль:
IncorrectPassword=Уведзены пароль няправільны. Паспрабуйце яшчэ раз.
WizardLicense=Ліцэнзійнае пагадненне
LicenseLabel=Прачытайце наступную важную інфармацыю перад працягам.
LicenseLabel3=Прачытайце ліцэнзійнае пагадненне. Каб працягнуць усталяванне, трэба прыняць яго ўмовы.
LicenseAccepted=Я &прымаю ўмовы пагаднення
LicenseNotAccepted=Я &не прымаю ўмовы пагаднення
WizardInfoBefore=Звесткі
InfoBeforeLabel=Прачытайце наступную важную інфармацыю перад працягам.
InfoBeforeClickLabel=Калі будзеце гатовыя працягнуць, націсніце «Далей».
WizardInfoAfter=Звесткі
InfoAfterLabel=Прачытайце наступную важную інфармацыю перад працягам.
InfoAfterClickLabel=Калі будзеце гатовыя працягнуць, націсніце «Далей».
WizardUserInfo=Звесткі пра карыстальніка
UserInfoDesc=Увядзіце звесткі пра сябе.
UserInfoName=&Імя карыстальніка:
UserInfoOrg=&Арганізацыя:
UserInfoSerial=&Серыйны нумар:
UserInfoNameRequired=Трэба ўвесці імя.
WizardSelectComponents=Выбар кампанентаў
SelectComponentsDesc=Якія кампаненты трэба ўсталяваць?
SelectComponentsLabel2=Адзначце патрэбныя кампаненты і зніміце адзнакі з непатрэбных. Каб працягнуць, націсніце «Далей».
FullInstallation=Поўнае ўсталяванне
CompactInstallation=Кампактнае ўсталяванне
CustomInstallation=Выбарачнае ўсталяванне
NoUninstallWarningTitle=Кампаненты ўжо існуюць
NoUninstallWarning=Усталёўшчык выявіў, што наступныя кампаненты ўжо ўсталяваныя:%n%n%1%n%nЗняцце адзнак не выдаліць гэтыя кампаненты.%n%nУсё роўна працягнуць?
ComponentSize1=%1 КБ
ComponentSize2=%1 МБ
ComponentsDiskSpaceGBLabel=Для выбраных кампанентаў трэба не менш за [gb] ГБ на дыску.
ComponentsDiskSpaceMBLabel=Для выбраных кампанентаў трэба не менш за [mb] МБ на дыску.
WizardSelectTasks=Выбар дадатковых задач
SelectTasksDesc=Якія дадатковыя задачы трэба выканаць?
SelectTasksLabel2=Выберыце дадатковыя задачы, якія трэба выканаць падчас усталявання [name], і націсніце «Далей».
WizardSelectProgramGroup=Выбар папкі меню «Пуск»
SelectStartMenuFolderDesc=Дзе размясціць ярлыкі праграмы?
SelectStartMenuFolderLabel3=Усталёўшчык створыць ярлыкі праграмы ў наступнай папцы меню «Пуск».
SelectStartMenuFolderBrowseLabel=Каб працягнуць, націсніце «Далей». Каб выбраць іншую папку, націсніце «Агляд».
MustEnterGroupName=Трэба ўвесці назву папкі.
GroupNameTooLong=Назва папкі або шлях занадта доўгія.
InvalidGroupName=Назва папкі няправільная.
BadGroupName=Назва папкі не можа змяшчаць наступныя знакі:%n%n%1
NoProgramGroupCheck2=&Не ствараць папку ў меню «Пуск»
ReadyMemoUserInfo=Звесткі пра карыстальніка:
DownloadingLabel2=Спампоўванне файлаў...
ButtonStopDownload=&Спыніць спампоўванне
StopDownload=Сапраўды спыніць спампоўванне?
ErrorDownloadAborted=Спампоўванне перапынена
ErrorDownloadFailed=Памылка спампоўвання: %1 %2
ErrorDownloadSizeFailed=Не ўдалося атрымаць памер: %1 %2
ErrorProgress=Няправільны прагрэс: %1 з %2
ErrorFileSize=Няправільны памер файла: чакалася %1, атрымана %2
ExtractingLabel=Распакоўванне файлаў...
ButtonStopExtraction=&Спыніць распакоўванне
StopExtraction=Сапраўды спыніць распакоўванне?
ErrorExtractionAborted=Распакоўванне перапынена
ErrorExtractionFailed=Памылка распакоўвання: %1
ArchiveIncorrectPassword=Пароль няправільны
ArchiveIsCorrupted=Архіў пашкоджаны
ArchiveUnsupportedFormat=Фармат архіва не падтрымліваецца
ClickFinish=Націсніце «Завяршыць», каб выйсці з усталёўшчыка.
AbortRetryIgnoreSelectAction=Выберыце дзеянне
AbortRetryIgnoreRetry=&Паспрабаваць яшчэ раз
AbortRetryIgnoreIgnore=&Ігнараваць памылку і працягнуць
AbortRetryIgnoreCancel=Скасаваць усталяванне
RetryCancelSelectAction=Выберыце дзеянне
RetryCancelRetry=&Паспрабаваць яшчэ раз
RetryCancelCancel=Скасаваць
StatusDownloadFiles=Спампоўванне файлаў...
FileAbortRetryIgnoreSkipNotRecommended=&Прапусціць гэты файл (не рэкамендуецца)
FileAbortRetryIgnoreIgnoreNotRecommended=&Ігнараваць памылку і працягнуць (не рэкамендуецца)
SourceVerificationFailed=Праверка зыходнага файла скончылася памылкай: %1
VerificationSignatureDoesntExist=Файл подпісу «%1» не існуе
VerificationSignatureInvalid=Файл подпісу «%1» няправільны
VerificationKeyNotFound=Файл подпісу «%1» выкарыстоўвае невядомы ключ
VerificationFileNameIncorrect=Назва файла няправільная
VerificationFileTagIncorrect=Тэг файла няправільны
VerificationFileSizeIncorrect=Памер файла няправільны
VerificationFileHashIncorrect=Кантрольная сума файла няправільная
ExistingFileReadOnly2=Існуючы файл немагчыма замяніць, бо ён пазначаны як «толькі для чытання».
ExistingFileReadOnlyRetry=&Зняць атрыбут «толькі для чытання» і паўтарыць
ExistingFileReadOnlyKeepExisting=&Пакінуць існуючы файл
FileExistsSelectAction=Выберыце дзеянне
FileExists2=Файл ужо існуе.
FileExistsOverwriteExisting=&Перазапісаць існуючы файл
FileExistsKeepExisting=&Пакінуць існуючы файл
FileExistsOverwriteOrKeepAll=&Паўтараць гэта для наступных канфліктаў
ExistingFileNewerSelectAction=Выберыце дзеянне
ExistingFileNewer2=Існуючы файл навейшы за файл, які спрабуе ўсталяваць праграма.
ExistingFileNewerOverwriteExisting=&Перазапісаць існуючы файл
ExistingFileNewerKeepExisting=&Пакінуць існуючы файл (рэкамендуецца)
ExistingFileNewerOverwriteOrKeepAll=&Паўтараць гэта для наступных канфліктаў
ErrorDownloading=Падчас спампоўвання файла адбылася памылка:
ErrorExtracting=Падчас распакоўвання архіва адбылася памылка:
UninstallDisplayNameMark=%1 (%2)
UninstallDisplayNameMarks=%1 (%2, %3)
UninstallDisplayNameMark32Bit=32-бітная
UninstallDisplayNameMark64Bit=64-бітная
UninstallDisplayNameMarkAllUsers=Усе карыстальнікі
UninstallDisplayNameMarkCurrentUser=Бягучы карыстальнік
StatusUninstalling=Выдаленне %1...
ShutdownBlockReasonInstallingApp=Усталёўваецца %1.
ShutdownBlockReasonUninstallingApp=Выдаляецца %1.
NameAndVersion=%1, версія %2
AdditionalIcons=Дадатковыя ярлыкі:
CreateDesktopIcon=Стварыць ярлык на &працоўным стале
CreateQuickLaunchIcon=Стварыць ярлык у панэлі &хуткага запуску
ProgramOnTheWeb=%1 у інтэрнэце
UninstallProgram=Выдаліць %1
LaunchProgram=Запусціць %1
AssocFileExtension=&Звязаць %1 з пашырэннем файла %2
AssocingFileExtension=Звязванне %1 з пашырэннем файла %2...
AutoStartProgramGroupDescription=Аўтазапуск:
AutoStartProgram=Аўтаматычна запускаць %1
AddonHostProgramNotFound=Не ўдалося знайсці %1 у выбранай папцы.%n%nУсё роўна працягнуць?
